/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FinancialServicesRouteImport } from './routes/financial-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessAcademyRouteImport } from './routes/business-academy'
import { Route as AgencyNetworkRouteImport } from './routes/agency-network'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialServicesRoute = FinancialServicesRouteImport.update({
  id: '/financial-services',
  path: '/financial-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAcademyRoute = BusinessAcademyRouteImport.update({
  id: '/business-academy',
  path: '/business-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyNetworkRoute = AgencyNetworkRouteImport.update({
  id: '/agency-network',
  path: '/agency-network',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency-network': typeof AgencyNetworkRoute
  '/business-academy': typeof BusinessAcademyRoute
  '/contact': typeof ContactRoute
  '/financial-services': typeof FinancialServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency-network': typeof AgencyNetworkRoute
  '/business-academy': typeof BusinessAcademyRoute
  '/contact': typeof ContactRoute
  '/financial-services': typeof FinancialServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency-network': typeof AgencyNetworkRoute
  '/business-academy': typeof BusinessAcademyRoute
  '/contact': typeof ContactRoute
  '/financial-services': typeof FinancialServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency-network'
    | '/business-academy'
    | '/contact'
    | '/financial-services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency-network'
    | '/business-academy'
    | '/contact'
    | '/financial-services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/agency-network'
    | '/business-academy'
    | '/contact'
    | '/financial-services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyNetworkRoute: typeof AgencyNetworkRoute
  BusinessAcademyRoute: typeof BusinessAcademyRoute
  ContactRoute: typeof ContactRoute
  FinancialServicesRoute: typeof FinancialServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-services': {
      id: '/financial-services'
      path: '/financial-services'
      fullPath: '/financial-services'
      preLoaderRoute: typeof FinancialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-academy': {
      id: '/business-academy'
      path: '/business-academy'
      fullPath: '/business-academy'
      preLoaderRoute: typeof BusinessAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency-network': {
      id: '/agency-network'
      path: '/agency-network'
      fullPath: '/agency-network'
      preLoaderRoute: typeof AgencyNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyNetworkRoute: AgencyNetworkRoute,
  BusinessAcademyRoute: BusinessAcademyRoute,
  ContactRoute: ContactRoute,
  FinancialServicesRoute: FinancialServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
